create table IF not exists products (
    id bigint generated by default as identity,
    code varchar(10) not null unique,
    name varchar(255) not null,
    price_eur numeric(38,2) not null,
    available boolean not null,
    primary key (id)
)