name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_ORGANISATION: mikorpar
  SONAR_PROJECT_KEY: mikorpar_product-service

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Create keystore for JWT signature
        uses: ./.github/actions/generate-jwt-signature-requirements
        env:
          JWT_KEYSTORE_PWD: ${{ secrets.JWT_KEYSTORE_PWD }}

      - name: Build and run tests
        run: ./mvnw test

  run-sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Create keystore with JWT signature requirements
        uses: ./.github/actions/generate-jwt-signature-requirements
        env:
          JWT_KEYSTORE_PWD: ${{ secrets.JWT_KEYSTORE_PWD }}

      - name: Run tests and CI-based analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >-
          ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
          -Dsonar.organization=${{ env.SONAR_ORGANISATION }}
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Pcoverage
