name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Create private key and certificate for JWT signature
        run: |
          openssl req -x509 \
          -newkey rsa:2048 \
          -keyout src/main/resources/key.pem \
          -out src/main/resources/cert.pem \
          -days 365 \
          -nodes \
          -subj "/CN=ProductService"
          
          openssl pkcs12 -export \
          -inkey src/main/resources/key.pem \
          -in src/main/resources/cert.pem \
          -out src/main/resources/keystore.p12 \
          -name jtw_sign_key \
          -passout pass:${{ secrets.JWT_KEYSTORE_PWD }}
          
          rm src/main/resources/cert.pem src/main/resources/key.pem

      - name: Build and run tests
        run: mvn test